language: perl

install:
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n
  - cpanm -n https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/Clustericious-1.10_03.tar.gz

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"

script:
  - prove -lv t

sudo: false
